name: NewJoinMessage
version: '4.0'
main: com.joinleave.JoinleaveMessage
authors: [ Yanel, oled ]
description: this plugin is for join/leave message per player
website: https://zaxnetwork.xyz
loadbefore: [ViaBackwards]


listeners:
  - com.joinleave.FireworkPlayerJoinListener
  - com.joinleave.PlayerJoinListener



resources:
  'Lang/':
    - 'english.yml'
    - 'germany.yml'
    - 'french.yml'
    - 'spanish.yml'
    - 'italian.yml'
    - 'chinese.yml'
    - 'japanese.yml'
    - 'korean.yml'
    - 'russian.yml'
    - 'DataLang.yml'


commands:
  njm:
    description: NewJoinMessage command
    usage: /njm [help]
    tab-complete: true

permissions:
  joinleave.set.join:
    description: Allows players to set their join message.
    default: op

  joinleave.set.leave:
    description: Allows players to set their leave message.
    default: op

  joinleave.reload:
    description: Allows players to reload the plugin.
    default: op

  joinleave.gui:
    description: Allows players to open the GUI.
    default: op

  joinleave.setplayer:
    description: Allows players to set join/leave messages for another player.
    default: op

  joinleave.clearplayer:
    description: Allows players to clear join/leave messages for another player.
    default: op

  joinleave.info:
    description: Allows players to view player information.
    default: op

  joinleave.update:
    description: Check for update.
    default: op
